---
name: Build and Push Golang image to AWS ECR
on:
  push:
    branches: [ master ]
jobs:
  build-and-push:
    name: Build and Push to AWS ECR 
    runs-on: ubuntu-latest 
    steps: 
    - name: SCM Checkout
      uses: actions/checkout@v2

    - name: Configure the AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 

    - name: Login to the AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, Tag and Push the image to AWS ECR
      id: build-image
      env: 
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: go-app
        IMAGE_TAG: latest
      run: 
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
    - name: Push the image to AWS ECR
      id: push-image
      env: 
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: go-app
        IMAGE_TAG: latest
      run:
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    - name: Deploy image to EC2 instance
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: go-app
        IMAGE_TAG: latest
        AWS_DEFAULT_REGION: us-east-1
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_PUBLIC_IP }}
        username: ubuntu
        key: ${{ secrets.PRIVATE_SSH_KEY }}
        envs: PRIVATE_SSH_KEY,REGISTRY, REPOSITORY, IMAGE_TAG, AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_DEFAULT_REGION
        scripts: |- 
          sudo apt update
          sudo apt install docker.io -y
          sudo apt install awscli -y
          sudo $(aws ecr get-login --no-include-email --region us-east-1);
          sudo docker stop goappcontainer || true
          sudo docker rm goappcontainer || true
          sudo docker pull $REGISTRY/$REPOSITORY:$IMAGE_TAG
          sudo docker run -d --name goappcontainer -p 5000:5000  $REGISTRY/$REPOSITORY:$IMAGE_TAG
